#!/bin/bash

# Copyright 2014-2015 RogentOS Linux Group
# LICENSE: GPL v2.0

rm /etc/entropy/repositories.conf.d/README
for i in $(ls /etc/entropy/repositories.conf.d/ | cut -d '.' -f 1 | sort -u | cut -d "_" -f 2); do
	equo repo mirrorsort $i
done

equo update
